variables:
  # SYNOPSYS_DC: synopsys-2022.03 dcnxt_shell
  QuestaModule:     "questa/2025.3"
  BenderModule:     "bender/0.28.2"

before_script:
  - module purge
  - module load ${BenderModule} ${QuestaModule}
  - module list
  - mkdir -p build

vsim:
  stage: build
  script:
    - echo "Running VSIM job with VSIM_VER='$VSIM_VER'"
    - export ARTIFACT="vsim-$VSIM_VER"
    - >
      cd build && ../scripts/compile_vsim.sh 
  artifacts:
    paths:
      - build/work
    expire_in: 1h

# synopsys_dc:
#   stage: build
#   script:
#     - >
#       if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup synopsys_dc; then
#         cd build && ../scripts/synth.sh
#         $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert synopsys_dc
#       fi

# fuse_xsim:
#   stage: build
#   allow_failure: true
#   timeout: 5 minutes
#   script:
#     - bender sources
#     - /usr/local/anaconda3/bin/python3 -m pip install fusesoc --user
#     - mkdir fusesoc && cd fusesoc
#     - $HOME/.local/bin/fusesoc library add axi ..
#     - $HOME/.local/bin/fusesoc core list
#     - vitis-2022.1-zr $HOME/.local/bin/fusesoc run --tool xsim --target sim --no-export pulp-platform.org::axi:$(cat ../VERSION | sed s/-/./g)

# verilator_lint:
#   stage: build
#   variables:
#     VERILATOR: verilator-5.020 verilator
#   script:
#     - scripts/run_verilator.sh

.run_vsim: &run_vsim
  stage: test
  needs:
    - vsim
  script:
    - export ARTIFACT="$TEST_MODULE-vsim_$VSIM_VER"
    - cd build
    - ../scripts/run_vsim.sh --random-seed "$TEST_MODULE"
    - touch "$ARTIFACT.tested"
  parallel:
    matrix:
      - VSIM_VER: ['2025.3']

axi_addr_test:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_addr_test

axi_atop_filter:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_atop_filter

axi_cdc:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_cdc

axi_delayer:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_delayer

axi_dw_downsizer:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_dw_downsizer

axi_dw_upsizer:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_dw_upsizer

axi_fifo:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_fifo

axi_isolate:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_isolate

axi_iw_converter:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_iw_converter

axi_lite_dw_converter:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_dw_converter

axi_lite_mailbox:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_mailbox

axi_lite_regs:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_regs

axi_lite_to_apb:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_to_apb

axi_lite_to_axi:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_to_axi

axi_lite_xbar:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_lite_xbar

axi_modify_address:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_modify_address

axi_serializer:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_serializer

axi_sim_mem:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_sim_mem

axi_to_axi_lite:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_to_axi_lite

axi_to_mem_banked:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_to_mem_banked

axi_xbar:
  <<: *run_vsim
  variables:
    TEST_MODULE: axi_xbar
